.\" IPA-GPO-INSTALL - Prepare FreeIPA for Group Policy Management
.\"
.\" Copyright (C) 2025 BaseALT Ltd.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH IPA-GPO-INSTALL 8
.
.SH NAME
ipa-gpo-install \- Prepare FreeIPA for Group Policy Management
.
.SH SYNOPSIS
\fBipa-gpo-install\fP [ --check-only ] [ --debuglevel \fILEVEL\fP ]
.
.SH DESCRIPTION
.B ipa-gpo-install
Prepares a FreeIPA server for Group Policy Management by extending the LDAP schema
with Group Policy related object classes and creating the necessary directory structure.

The utility performs several checks and necessary actions:
.IP \(bu 4
Extends the IPA LDAP schema with Group Policy related object classes
.IP \(bu 4
Installs AD Trust support if not already installed
.IP \(bu 4
Creates the SYSVOL directory structure
.IP \(bu 4
Sets up the SYSVOL Samba share
.
.SH OPTIONS
.TP
\fB--check-only\fP
Only perform checks without making changes.
.TP
\fB--debuglevel \fILEVEL\fR
Set the debug level: 0=errors, 1=warnings, 2=debug. Default is 0.
.
.SH "EXIT CODES"
.TP
\fB0\fR
Application exited successfully.
.TP
\fB1\fR
An error occurred during operation.
.
.SH FILES
.TP
\fB/var/log/freeipa/ipa-gpo-install.log\fR
Log file for ipa-gpo-install.
.TP
\fB/var/lib/freeipa/sysvol\fR
SYSVOL directory for Group Policy storage.
.TP
\fB/etc/samba/smb.conf\fR
Samba configuration file.
.
.SH REQUIREMENTS
This utility requires a properly installed and configured FreeIPA server. It must be run
as root on the FreeIPA server and requires a valid Kerberos ticket for a user who is a domain
administrator or a member of the 'admins' group.
.
.SH "SEE ALSO"
ipa-adtrust-install(1), ipa(1), kinit(1)
.
.SH BUGS
Please report any bugs to the ALT Linux Bugzilla at https://bugzilla.altlinux.org/ for this package.
.
.SH AUTHOR
skachedubov@altlinux.org